#Alamanda Ardana - Program Kuis Bangun Datar
#----------------------------------------

#Menanyakan Nama dan NIM User
nama_user = input('Nama Kamu        : ')
nim_user = int(input('NIM Kamu         : '))
print()

#Membuat Sapaan dan Judul Program
print(".....................................................")
print(".  Hai,",nama_user, "yang NIM-nya", nim_user, "!!!                  .")
print(".  Selamat datang di KUIS BANGUN DATAR              .")
print(".....................................................")
print()

#Soal Nomor 1
print("SOAL NOMOR 1 :")
print("Diketahui sisi = 6. Sebutkan nama bangun datar itu, serta hitunglah luas bangun datar tersebut!")
print()
print("JAWAB :")
nama_bangunDatar1 = input("Nama Bangun Datar = ")
sisi1_1 = int(input("Sisi = "))
sisi2_1 = int(input("Sisi = "))
print()
print ("KESIMPULAN :")
print("Nama bangun datar tersebut adalah", nama_bangunDatar1, "dan luas dari bangun datar tersebut adalah", sisi1_1 * sisi2_1)
print()
print("-------------------------------------------------------------------------------------------------------------------------------------")
print()

#Soal Nomor 2
print("SOAL NOMOR 2 :")
print("Diketahui alas = 7 dan tinggi = 8. Bangun datar itu memiliki tiga sisi. Sebutkan nama bangun datar itu, serta hitunglah luas bangun datar tersebut!")
print()
print("JAWAB :")
nama_bangunDatar2 = input("Nama Bangun Datar = ")
alas1_2 = int(input("Alas = "))
tinggi1_2 = int(input("Tinggi = "))
print()
print ("KESIMPULAN :")
print("Nama bangun datar tersebut adalah", nama_bangunDatar2, "dan luas dari bangun datar tersebut adalah", alas1_2 * tinggi1_2 / 2)
print()
print("-------------------------------------------------------------------------------------------------------------------------------------")
print()

#Soal Nomor 3
print("SOAL NOMOR 3 :")
print("Diketahui panjang = 4 dan lebar = 9. Sebutkan nama bangun datar itu, serta hitunglah luas bangun datar tersebut!")
print()
print("JAWAB :")
nama_bangunDatar3 = input("Nama Bangun Datar = ")
panjang1_3 = int(input("Panjang = "))
lebar1_3 = int(input("Lebar = "))
print()
print ("KESIMPULAN :")
print("Nama bangun datar tersebut adalah", nama_bangunDatar3, "dan luas dari bangun datar tersebut adalah", panjang1_3 * lebar1_3)
print()
print("-------------------------------------------------------------------------------------------------------------------------------------")
print()

#Soal Nomor 4
print("SOAL NOMOR 4 :")
print("Diketahui jari-jari = 56. Sebutkan nama bangun datar itu, serta hitunglah luas bangun datar tersebut!")
print()
print("JAWAB :")
nama_bangunDatar4 = input("Nama Bangun Datar = ")
phi1_4 = float(input("π = "))
jarijari1_4 = int(input("r = "))
print()
print ("KESIMPULAN :")
print("Nama bangun datar tersebut adalah", nama_bangunDatar4, "dan luas dari bangun datar tersebut adalah", phi1_4 * jarijari1_4 * jarijari1_4)
print()
print("-------------------------------------------------------------------------------------------------------------------------------------")
print()

#Soal Nomor 5
print("SOAL NOMOR 5 :")
print("Diketahui diagonal I = 4 dan diagonal II = 8. Sebutkan nama bangun datar itu, serta hitunglah luas bangun datar tersebut!")
print()
print("JAWAB :")
nama_bangunDatar5 = input("Nama Bangun Datar = ")
diagonal1_5 = int(input("Diagonal I = "))
diagonal2_5 = int(input("Diagonal II = "))
print()
print ("KESIMPULAN :")
print("Nama bangun datar tersebut adalah", nama_bangunDatar5, "dan luas dari bangun datar tersebut adalah", diagonal1_5 * diagonal2_5 / 2)
print()
print("-------------------------------------------------------------------------------------------------------------------------------------")
print()

#Soal Nomor 6
print("SOAL NOMOR 6 :")
print("Diketahui sisi AB dan CD sejajar. Sisi AB = 6, sisi CD = 8, dan tinggi = 3. Sebutkan nama bangun datar itu, serta hitunglah luas bangun datar tersebut!")
print()
print("JAWAB :")
nama_bangunDatar6 = input("Nama Bangun Datar = ")
sisiAB_6 = int(input("Sisi AB = "))
sisiCD_6 = int(input("Sisi CD = "))
tinggi1_6 = int(input("Tinggi = "))
print()
print ("KESIMPULAN :")
print("Nama bangun datar tersebut adalah", nama_bangunDatar6, "dan luas dari bangun datar tersebut adalah", ((sisiAB_6 + sisiCD_6) * tinggi1_6 / 2))
print()
print("-------------------------------------------------------------------------------------------------------------------------------------")
print()

#Soal Nomor 7
print("SOAL NOMOR 7 :")
print("Diketahui sebuah jajar genjang dengan alas = 9 dan tinggi = 7. Hitunglah luas bangun datar tersebut!")
print()
print("JAWAB :")
alas1_7 = int(input("Alas = "))
tinggi1_7 = int(input("Tinggi = "))
print()
print ("KESIMPULAN :")
print("Luas dari jajar genjang tersebut adalah", alas1_7 * tinggi1_7)
print()
print("-------------------------------------------------------------------------------------------------------------------------------------")
print()

#Membuat Kalimat Penutup
print("...................................................")
print(".                                                 .")
print(".  Terima kasih karena sudah mencoba kuis ini :)  .")
print(".                                                 .")
print("...................................................")
print()
print()